### ISSUE TITLE
Support php 7.1

### ISSUE THREAD

**Issue by tiamo** [cloudflare/Cloudflare-Magento#67] opened 2017-11-28 18:45 UTC
When I tried to install module via composer, I got this error:
Could not find package cloudflare/cloudflare-magento at any version matching your PHP version 7.1.12.0

**Comment by thellimist** [comment] 2017-11-28 20:58
This is caused by https://github.com/cloudflare/Cloudflare-Magento/blob/master/composer.json#L18

https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

**Comment by tiamo** [comment] 2017-11-28 23:35
I know, I just proposed to add php 7.1

**Comment by thellimist** [comment] 2017-11-29 18:53
@tiamo I've re-released in packagist. Could you give it a try?

https://packagist.org/packages/cloudflare/cloudflare-magento

Thanks

**Comment by tiamo** [comment] 2017-11-30 10:18
Yep, now it works. Thanks

**Closed** 2017-11-30 11:43 UTC
