### ISSUE TITLE
Unable to install on Magento 2.1.2 through composer

### ISSUE THREAD

**Issue by mehh** [cloudflare/Cloudflare-Magento#36] opened 2016-11-26 03:21 UTC
```[username2@host www]$ composer require cloudflare/cloudflare-magento
Using version ^1.0 for cloudflare/cloudflare-magento
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cloudflare/cloudflare-magento 1.0.8 requires cloudflare/cloudflare-plugin-backend 1.1.7 -> satisfiable by cloudflare/cloudflare-plugin-backend[1.1.7].
    - cloudflare/cloudflare-magento 1.0.9 requires cloudflare/cloudflare-plugin-backend 1.1.7 -> satisfiable by cloudflare/cloudflare-plugin-backend[1.1.7].
    - Conclusion: don't install cloudflare/cloudflare-plugin-backend 1.1.7
    - cloudflare/cloudflare-magento 1.0.7 requires cloudflare/cloudflare-plugin-backend 1.1.3 -> satisfiable by cloudflare/cloudflare-plugin-backend[1.1.3].
    - Conclusion: don't install cloudflare/cloudflare-plugin-backend 1.1.3
    - cloudflare/cloudflare-magento 1.0.6 requires cloudflare/cloudflare-plugin-backend 1.1.1 -> satisfiable by cloudflare/cloudflare-plugin-backend[1.1.1].
    - Conclusion: don't install cloudflare/cloudflare-plugin-backend 1.1.1
    - cloudflare/cloudflare-magento 1.0.4 requires cloudflare/cloudflare-plugin-backend 1.0.4 -> satisfiable by cloudflare/cloudflare-plugin-backend[1.0.4].
    - cloudflare/cloudflare-magento 1.0.5 requires cloudflare/cloudflare-plugin-backend 1.0.4 -> satisfiable by cloudflare/cloudflare-plugin-backend[1.0.4].
    - Conclusion: don't install cloudflare/cloudflare-plugin-backend 1.0.4
    - Conclusion: don't install cloudflare/cloudflare-magento 1.0.3
    - cloudflare/cloudflare-magento 1.0.0 requires cloudflare/cloudflare-plugin-backend 1.0.1 -> satisfiable by cloudflare/cloudflare-plugin-backend[1.0.1].
    - Conclusion: remove guzzlehttp/guzzle 6.2.2
    - Installation request for cloudflare/cloudflare-magento ^1.0 -> satisfiable by cloudflare/cloudflare-magento[1.0.0, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].
    - Conclusion: don't install guzzlehttp/guzzle 6.2.2
    - cloudflare/cloudflare-plugin-backend 1.0.1 requires guzzlehttp/guzzle ~5.0 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.0, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[5.0.1, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[5.0.2, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[5.0.3, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[5.3.1, 6.2.2].
    - Installation request for guzzlehttp/guzzle (locked at 6.2.2) -> satisfiable by guzzlehttp/guzzle[6.2.2].


Installation failed, reverting ./composer.json to its original content.```

**Comment by jwineman** [comment] 2016-11-26 14:34
Hi,

Thanks for reporting this!  I'll try reproducing Monday and will update here when I know more!

Thanks,
John

**Comment by jwineman** [comment] 2016-11-28 18:29
So the issue is composer only allows for one version of guzzle to be installed.  However Magneto 2.1 doesn't depend on guzzle, do you have another mageneto plugin that does depend on guzzle?  Do you know which it is?  I'm looking into whether we can upgrade to 6.0 or not.

**Comment by firstred** [comment] 2016-12-20 01:27
Having the same problem here. None of my other plugins depend on Guzzle.

I think that `cloudflare/cloudflare-plugin-backend` and `cloudflare/cloudflare-magento` themselves have a dependency conflict.

Upgrading this plugin to use Guzzle 6 would be the best solution, I think.

**Comment by firstred** [comment] 2016-12-20 01:39
More info:
`cloudflare/cloudflare-plugin-backend` has been downgraded to 3.9, but the Magento plugin still depends on 5.0

**Comment by jwineman** [comment] 2016-12-21 13:26
@firstred thank you, this more information was helpful! `cloudflare/cloudflare-plugin-backend` is a library all of our PHP based integrations share.  Guzzle was downgraded to 3.9 because WordPress required support for lower versions of PHP.  

However we're in the process of switching the HTTP client for WordPress and I should be able to bump the Guzzle version up soon.  I'll report back when I have a fix!

**Comment by jwineman** [comment] 2017-04-02 23:43
Fixed in https://github.com/cloudflare/Cloudflare-Magento/pull/47

Can you upgrade to 1.1.1 and let me know if this is resolved please?

**Closed by jwineman** 2017-04-02 23:43 UTC
