### ISSUE TITLE
Cannot install Magento 2.1.4 with plugin enabled

### ISSUE THREAD

**Issue by navarr** [cloudflare/Cloudflare-Magento#39] opened 2017-02-24 14:17 UTC
With the cloudflare magento plugin required, a fresh installation of Magento 2.1.4 fails.

Error message: (vagrant/puppet encoded)

```
==> default: Notice: /Stage[main]/Magento/Exec[Install Magento]/returns: Running schema recurring...PHP Fatal error:  Uncaught Error: Cannot instantiate interface CF\Integration\IntegrationInterface in /var/www/Magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73
==> default: Notice: /Stage[main]/Magento/Exec[Install Magento]/returns: Stack trace:
==> default: Notice: /Stage[main]/Magento/Exec[Install Magento]/returns: #0 /var/www/Magento/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('CF\\Integration\\...')
==> default: Notice: /Stage[main]/Magento/Exec[Install Magento]/returns: #1 /var/www/Magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('CF\\Integration\\...')
==> default: Notice: /Stage[main]/Magento/Exec[Install Magento]/returns: #2 /var/www/Magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'CF\\Integration\\...', NULL, 'integration', 'CloudFlare\\Plug...')
==> default: Notice: /Stage[main]/Magento/Exec[Install Magento]/returns: #3 /var/www/Magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('CloudFlare\\Plug...', Array, Array)
==> default: Notice: /Stage[main]/Magento/Exec[Install Magento]/returns: #4 /var/www/Magento/vendor/magento/framework/Obj in /var/www/Magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73
```

**Comment by jwineman** [comment] 2017-02-24 23:50
Hi,

Are you in development or production mode?
What bin/magento commands did you run beforehand?

**Comment by navarr** [comment] 2017-02-25 00:02
So this is happening as part of our deployment process.  So no Magento commands have been run, there's no var files, etc.

The error occurs during a setup:install.

MariaDB 10, PHP 5.6

It was also occurring during a setup:upgrade on the server, but that's harder to get a good reproducible case for.

**Comment by jwineman** [comment] 2017-02-25 00:14
I think this is a dupe or at least related to https://github.com/cloudflare/Cloudflare-Magento/issues/34

I'm looking into these issues next week.  I'll leave this open and update when I know more.  

I'm able to reproduce though.

**Comment by ooples** [comment] 2017-03-29 16:53
I'm having this same issue as well. I can't get cloudflare to work with magento 2.1.4

**Comment by jwineman** [comment] 2017-04-02 23:43
Fixed in https://github.com/cloudflare/Cloudflare-Magento/pull/47

Can you upgrade to 1.1.1 and let me know if this is resolved please?

**Closed by jwineman** 2017-04-02 23:43 UTC
